package cloud.nino.nino.service.dto.custom;

import javax.validation.constraints.NotNull;
import java.io.Serializable;

/**
 * Created by dawit on 25/09/2018.
 */
public class AutogeneratedUserInput implements Serializable{
    @NotNull
    private Boolean privacy;

    public Boolean getPrivacy() {
        return privacy;
    }

    public void setPrivacy(Boolean privacy) {
        this.privacy = privacy;
    }
}
