version: '3'
services:
    nino-app:
        image: dawitabate/we-plant:001
        volumes:
            - ~/nino-images/:/nino-images/
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://nino-postgresql:5432/we-plant
            - SPRING_DATASOURCE_USERNAME=we-plant
            - SPRING_DATASOURCE_PASSWORD=TuttoVerde!2018!
            - SPRING_MAIL_PASSWORD=verde6bello!
            - SERVER_PORT=8080
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
        networks:
            - nino
        links:
            - nino-postgresql
    nino-postgresql:
        image: nino-postgresql
        volumes:
             - /var/lib/postgresql/data/:/var/lib/postgresql/data/
             - ~/we-plant/postgresql/aws/:/root/.aws
             - ~/we-plant/postgresql/script/:/root/script
        environment:
            - POSTGRES_USER=we-plant
            - POSTGRES_PASSWORD=TuttoVerde!2018!
        ports:
            - 5432:5432
        networks:
            - nino
networks:
    nino:
        driver: "bridge"
