version: '3'
services:
    nino-postgresql:
        image: postgres:10.4
        volumes:
             - ./data/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=we-plant
            - POSTGRES_PASSWORD=WePlantPass!2021!
        ports:
            - 5432:5432
